const http = require('http');
const fs = require('fs');
const path = require('path');
const { URL } = require('url');
const PORT = process.env.PORT || 3000;
const ROOT = __dirname, PUBLIC = path.join(ROOT,'public');
const KEY = () => process.env.OPENAI_API_KEY;
function send(res,status,body,type='text/html; charset=utf-8'){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store'});res.end(body)}
async function readJson(req){return await new Promise((resolve,reject)=>{let d='';req.on('data',c=>{d+=c;if(d.length>8e6)req.destroy()});req.on('end',()=>{try{resolve(d?JSON.parse(d):{})}catch(e){reject(e)}});req.on('error',reject)})}
async function oa(pathname, options={}){if(!KEY()) throw new Error('OPENAI_API_KEY is not configured on the server.');const r=await fetch('https://api.openai.com'+pathname,{...options,headers:{Authorization:`Bearer ${KEY()}`,...(options.headers||{})}});const ct=r.headers.get('content-type')||'';const data=ct.includes('application/json')?await r.json():await r.arrayBuffer();if(!r.ok)throw new Error(data?.error?.message||`OpenAI API error ${r.status}`);return {data,ct}}
async function aiChat(messages,system){const model=process.env.OPENAI_MODEL||'gpt-5.6-luna';const body={model,input:[...(system?[{role:'system',content:system}]:[]),...messages.map(m=>({role:m.role||'user',content:m.content}))]};const x=await oa('/v1/responses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=x.data;let out=d.output_text||'';if(!out&&Array.isArray(d.output)){out=d.output.flatMap(o=>o.content||[]).map(c=>c.text||'').join('')}return out}
async function api(req,res,url){
 try{
  if(req.method==='POST'&&url.pathname==='/api/ai'){const b=await readJson(req);const text=await aiChat([{role:'user',content:b.prompt||''}],b.system||'');return send(res,200,JSON.stringify({text}),'application/json')}
  if(req.method==='GET'&&url.pathname==='/api/status')return send(res,200,JSON.stringify({ok:true,aiConfigured:!!KEY(),model:process.env.OPENAI_MODEL||'gpt-5.6-luna',imageModel:process.env.OPENAI_IMAGE_MODEL||'gpt-image-2',videoModel:process.env.OPENAI_VIDEO_MODEL||'sora-2'}),'application/json');
  if(req.method==='POST'&&url.pathname==='/api/chat'){const b=await readJson(req);const content=await aiChat(b.messages||[{role:'user',content:b.prompt||''}],b.system||'');return send(res,200,JSON.stringify({content}),'application/json')}
  if(req.method==='POST'&&url.pathname==='/api/prompt'){const b=await readJson(req);const content=await aiChat([{role:'user',content:`Create a high-quality ready-to-use prompt. Task: ${b.task}. Target: ${b.mode||'General AI'}. Language: ${b.language||'Hindi'}. Return only the improved prompt.`}],'You are an expert prompt engineer.');return send(res,200,JSON.stringify({content}),'application/json')}
  if(req.method==='POST'&&url.pathname==='/api/writer'){const b=await readJson(req);const content=await aiChat([{role:'user',content:b.instruction||''}],`You are an expert professional writer. Write in ${b.language||'Hindi'} with a ${b.tone||'Professional'} tone.`);return send(res,200,JSON.stringify({content}),'application/json')}
  if(req.method==='POST'&&url.pathname==='/api/code'){const b=await readJson(req);const content=await aiChat([{role:'user',content:`Write code for: ${b.instruction}. Language: ${b.language||'C'}. Explain simply and include example/output.`}],'You are a programming tutor. Give correct beginner-friendly code.');return send(res,200,JSON.stringify({content}),'application/json')}
  if(req.method==='POST'&&url.pathname==='/api/translate'){const b=await readJson(req);const content=await aiChat([{role:'user',content:`Translate from ${b.from} to ${b.to}. Return only translation:\n${b.text}`}],'You are a precise translator.');return send(res,200,JSON.stringify({content}),'application/json')}
  if(req.method==='POST'&&url.pathname==='/api/image'){const b=await readJson(req);const payload={model:process.env.OPENAI_IMAGE_MODEL||'gpt-image-2',prompt:b.prompt,size:b.size||'1024x1024'};const x=await oa('/v1/images/generations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const item=x.data.data?.[0]||{};return send(res,200,JSON.stringify({b64:item.b64_json||null,url:item.url||null}),'application/json')}
  if(req.method==='POST'&&url.pathname==='/api/video'){const b=await readJson(req);const form=new FormData();form.append('model',process.env.OPENAI_VIDEO_MODEL||'sora-2');form.append('prompt',b.prompt);form.append('seconds',String(b.seconds||'4'));form.append('size',b.size||'1280x720');const x=await oa('/v1/videos',{method:'POST',body:form});return send(res,200,JSON.stringify(x.data),'application/json')}
  if(req.method==='GET'&&url.pathname.startsWith('/api/video/')){const id=url.pathname.split('/').pop();const x=await oa('/v1/videos/'+encodeURIComponent(id));return send(res,200,JSON.stringify(x.data),'application/json')}
  if(req.method==='GET'&&url.pathname.startsWith('/api/video-content/')){const id=url.pathname.split('/').pop();const x=await oa('/v1/videos/'+encodeURIComponent(id)+'/content');return send(res,200,Buffer.from(x.data),x.ct||'video/mp4')}
  return send(res,404,JSON.stringify({error:'Not found'}),'application/json');
 }catch(e){return send(res,500,JSON.stringify({error:e.message}),'application/json')}
}
function serve(req,res,url){let f=url.pathname==='/'?'/index.html':url.pathname;f=path.normalize(f).replace(/^([.][.][\\/])+/, '');const full=path.join(PUBLIC,f);if(!full.startsWith(PUBLIC))return send(res,403,'Forbidden');fs.stat(full,(e,s)=>{if(e||!s.isFile())return send(res,404,'Not found');const ext=path.extname(full),types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8'};send(res,200,fs.readFileSync(full),types[ext]||'application/octet-stream')})}
http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host}`);u.pathname.startsWith('/api/')?await api(req,res,u):serve(req,res,u)}).listen(PORT,()=>console.log('Gen AI Studio on '+PORT));
